import csv

FIELDS = ['marque','nom','nb_plis','poids_g','epaisseur_mm','composition','pli1','pli2','pli3','pli4','pli5','pli6','pli7']

def b(marque, nom, nb, poids, ep, *plis):
    plis = [p for p in plis if p]
    return {'marque':marque,'nom':nom,'nb_plis':str(nb),'poids_g':str(poids),'epaisseur_mm':str(ep),
            'composition':'-'.join(plis),
            'pli1':plis[0] if len(plis)>0 else '','pli2':plis[1] if len(plis)>1 else '',
            'pli3':plis[2] if len(plis)>2 else '','pli4':plis[3] if len(plis)>3 else '',
            'pli5':plis[4] if len(plis)>4 else '','pli6':plis[5] if len(plis)>5 else '',
            'pli7':plis[6] if len(plis)>6 else ''}

DATA = [
# BUTTERFLY
b('Butterfly','Fan Zhendong ALC',7,87,5.8,'Koto','ALC','Limba','Kiri','Limba','ALC','Koto'),
b('Butterfly','Fan Zhendong Super ZLC',7,90,5.6,'Koto','SZLC','Limba','Kiri','Limba','SZLC','Koto'),
b('Butterfly','Fan Zhendong ZLC',7,86,5.5,'Koto','ZLC','Limba','Kiri','Limba','ZLC','Koto'),
b('Butterfly','Lin Gaoyuan ALC',7,87,5.7,'Koto','ALC','Limba','Kiri','Limba','ALC','Koto'),
b('Butterfly','Lin Yun-Ju Super ZLC',7,87,5.6,'Koto','SZLC','Limba','Kiri','Limba','SZLC','Koto'),
b('Butterfly','Timo Boll ALC',7,84,5.7,'Koto','ALC','Limba','Kiri','Limba','ALC','Koto'),
b('Butterfly','Timo Boll Spirit',7,89,5.7,'Koto','ALC','Limba','Kiri','Limba','ALC','Koto'),
b('Butterfly','Timo Boll ZLC',7,85,5.5,'Koto','ZLC','Limba','Kiri','Limba','ZLC','Koto'),
b('Butterfly','Timo Boll ZLF',7,83,5.4,'Koto','ZLF','Limba','Kiri','Limba','ZLF','Koto'),
b('Butterfly','Timo Boll W7',7,94,6.7,'Koto','Ayous','Ayous','Ayous','Ayous','Ayous','Koto'),
b('Butterfly','Viscaria',7,86,5.8,'Koto','ALC','Limba','Kiri','Limba','ALC','Koto'),
b('Butterfly','Viscaria Super ALC',7,89,5.7,'Koto','SALC','Limba','Kiri','Limba','SALC','Koto'),
b('Butterfly','Zhang Jike ALC',7,87,5.8,'Koto','ALC','Limba','Kiri','Limba','ALC','Koto'),
b('Butterfly','Zhang Jike Super ZLC',7,90,5.6,'Koto','SZLC','Limba','Kiri','Limba','SZLC','Koto'),
b('Butterfly','Zhang Jike ZLC',7,86,5.5,'Koto','ZLC','Limba','Kiri','Limba','ZLC','Koto'),
b('Butterfly','Innerforce Layer ALC',7,90,6.0,'Limba','Limba','ALC','Ayous','ALC','Limba','Limba'),
b('Butterfly','Innerforce Layer ZLC',7,85,5.7,'Limba','Limba','ZLC','Ayous','ZLC','Limba','Limba'),
b('Butterfly','Harimoto Tomokazu Innerforce ALC',7,88,6.0,'Limba','Limba','ALC','Ayous','ALC','Limba','Limba'),
b('Butterfly','Primorac',5,84,5.5,'Limba','Limba','Ayous','Limba','Limba'),
b('Butterfly','Primorac Carbon',5,89,7.0,'Hinoki','T5000','Kiri','T5000','Hinoki'),
b('Butterfly','Korbel Speed',5,89,5.6,'Koto','Limba','Ayous','Limba','Koto'),
b('Butterfly','Sardius',5,92,7.2,'Hinoki','T5000','Kiri','T5000','Hinoki'),
b('Butterfly','Schlager Carbon',5,93,7.4,'Cyprès','T5000','Kiri','T5000','Cyprès'),
b('Butterfly','Amultart',5,86,7.1,'Hinoki','ZLC','Kiri','ZLC','Hinoki'),
b('Butterfly','Garaydia ALC',5,85,6.9,'Hinoki','ALC','Kiri','ALC','Hinoki'),
b('Butterfly','Iolite',5,80,0.0,'Hinoki','ALC','Kiri','ALC','Hinoki'),
b('Butterfly','Supreme Speed',5,80,6.9,'Hinoki','ALC','Kiri','ALC','Hinoki'),
b('Butterfly','Apolonia ZLC',7,90,5.7,'Limba','Limba','ZLC','Ayous','ZLC','Limba','Limba'),
b('Butterfly','Ovtcharov Innerforce ALC',7,91,6.2,'Limba','Limba','ALC','Ayous','ALC','Limba','Limba'),
b('Butterfly','SK Carbon',5,79,5.2,'Koto','T5000','Kiri','T5000','Koto'),
b('Butterfly','SK7 Classic',7,90,6.8,'Limba','Ayous','Ayous','Ayous','Ayous','Ayous','Limba'),
# STIGA
b('Stiga','Allround Classic',5,85,5.1,'Limba','Ayous','Ayous','Ayous','Limba'),
b('Stiga','Allround Evolution',5,85,0,'Limba','Ayous','Ayous','Ayous','Limba'),
b('Stiga','Clipper',7,90,6.6,'Limba','Ayous','Ayous','Ayous','Ayous','Ayous','Limba'),
b('Stiga','Carbonado 145',7,78,5.8,'Limba','TeXtreme®','Ayous','Ayous','Ayous','TeXtreme®','Limba'),
b('Stiga','Carbonado 190',7,86,5.8,'Limba','TeXtreme®','Ayous','Ayous','Ayous','TeXtreme®','Limba'),
b('Stiga','Dynasty Carbon',7,89,5.8,'Koto','TeXtreme+®','Ayous','Ayous','Ayous','TeXtreme+®','Koto'),
b('Stiga','Infinity VPS V',5,85,6.0,'Limba','Epicéa','Ayous','Epicéa','Limba'),
b('Stiga','Offensive Classic WRB',5,80,5.2,'Limba','Epicéa','Ayous','Epicéa','Limba'),
b('Stiga','Ebenholz NCT V',5,92,5.5,'Ebène','Epicéa','Ayous','Epicéa','Ebène'),
b('Stiga','Emerald VPS V',5,92,6.0,'Ebène','Epicéa','Ayous','Epicéa','Ebène'),
b('Stiga','Eternity VPS V',5,92,6.3,'Limba','Epicéa','Ayous','Epicéa','Limba'),
b('Stiga','Legacy Carbon',7,89,0,'Limba','Energy Carbon 12k','Pin','Ayous','Pin','Energy Carbon 12k','Limba'),
b('Stiga','Rosewood NCT VII',7,97,6.9,'Palissandre','Ayous','Ayous','Ayous','Ayous','Ayous','Palissandre'),
b('Stiga','Allround Classic Carbon',7,85,0,'Limba','Ayous','Carbone','Ayous','Carbone','Ayous','Limba'),
b('Stiga','Nostalgic VII',7,90,6.3,'Wenge','Epicéa','Ayous','Ayous','Ayous','Epicéa','Wenge'),
b('Stiga','Intensity NCT',5,85,0,'Noyer','Epicéa','Ayous','Epicéa','Noyer'),
# DONIC
b('Donic','Waldner Allplay',5,85,0,'Limba','Limba','Ayous','Limba','Limba'),
b('Donic','Waldner Senso Carbon',7,85,0,'Limba','Aniégré','Carbone','Ayous','Carbone','Aniégré','Limba'),
b('Donic','Waldner Exclusive AR+',5,85,5.7,'Limba','Limba','Ayous','Limba','Limba'),
b('Donic','Waldner Legend Carbon',5,83,6.3,'Hinoki','Carbone','Kiri','Carbone','Hinoki'),
b('Donic','Waldner Carbopower',5,85,6.2,'Hinoki','ALC','Kiri','ALC','Hinoki'),
b('Donic','Baum Esprit',7,88,6.0,'Koto','Aramide Carbone','Ayous','Kiri','Ayous','Aramide Carbone','Koto'),
b('Donic','Appelgren Allplay',5,80,0,'Limba','Limba','Ayous','Limba','Limba'),
b('Donic','Persson Powerplay',7,90,5.9,'Koto','Feuille anti-vibration','Ayous','Ayous','Ayous','Feuille anti-vibration','Koto'),
b('Donic','Persson Seven',7,90,6.3,'Limba','Ayous','Ayous','Ayous','Ayous','Ayous','Limba'),
b('Donic','Original True Carbon',7,90,5.3,'Koto','Carbone Kevlar™','Ayous','Kiri','Ayous','Carbone Kevlar™','Koto'),
b('Donic','Crest OFF',9,88,5.9,'Limba','ZLC','Carbone','Limba','Kiri','Limba','Carbone'),
b('Donic','Burn OFF',5,90,0,'Acajou','Awan','Kiri','Awan','Acajou'),
b('Donic','Ovtcharov Carbospeed',5,87,6.8,'Hinoki','Carbone','Kiri','Carbone','Hinoki'),
b('Donic','Zhou Yu Three',7,85,5.7,'Koto','Aramide Carbone','Limba','Kiri','Limba','Aramide Carbone','Koto'),
b('Donic','Persson Exclusive OFF',5,85,5.9,'Limba','Koto','Kiri','Koto','Limba'),
# TIBHAR
b('Tibhar','Samsonov Force Pro Black Edition',7,88,6.7,'Limba','Ayous','Ayous','Ayous','Ayous','Ayous','Limba'),
b('Tibhar','Stratus Power Wood',5,85,6.0,'Limba','Limba','Ayous','Limba','Limba'),
b('Tibhar','Samsonov Alpha (new 2012)',5,85,5.9,'Limba','Meranti','Ayous','Meranti','Limba'),
b('Tibhar','IV L',4,90,7.4,'Ayous','Ayous','Ayous','Ayous'),
b('Tibhar','IV L Balsa',6,70,7.0,'Ayous','Okoumé','Balsa','Balsa','Okoumé','Ayous'),
b('Tibhar','IV S',5,90,6.8,'Ayous','Ayous','Ayous','Ayous','Ayous'),
b('Tibhar','Drinkhall Power Spin Carbon',7,88,5.6,'Koto','ALC','Ayous','Kiri','Ayous','ALC','Koto'),
b('Tibhar','Marcos Freitas',7,84,6.0,'Limba','ALC','Ayous','Kiri','Ayous','ALC','Limba'),
b('Tibhar','Zodiac Libra ZAC',7,85,6.0,'Limba','Ayous','ZAC','Ayous','ZAC','Ayous','Limba'),
b('Tibhar','Lebesson',5,85,5.7,'Limba','Acajou','Ayous','Acajou','Limba'),
b('Tibhar','Stratus Power Defense',5,84,5.3,'Robinier','Limba','Ayous','Limba','Robinier'),
b('Tibhar','Ikarus ALX',9,85,6.5,'Ayous','Ayous','Ayous','Texalium™','Kiri','Texalium™','Ayous'),
# ANDRO
b('Andro','Gauzy SL',7,91,6.1,'Ebène','Limba','Ayous','Samba rouge','Ayous','Limba','Ebène'),
b('Andro','Treiber CI OFF',7,90,6.1,'Limba','Ayous','Carbone Kevlar™','Kiri','Carbone Kevlar™','Ayous','Limba'),
b('Andro','Treiber K',7,90,0,'Koto','Carbone Kevlar™','Ayous','Kiri','Ayous','Carbone Kevlar™','Koto'),
b('Andro','Treiber Z',7,88,0,'Hinoki','ZLF','Koto','Ayous','Koto','ZLF','Hinoki'),
b('Andro','Kinetic Supreme OFF-',7,85,0,'Hinoki','ZLC','Ayous','Kiri','Ayous','ZLC','Hinoki'),
b('Andro','Ligna OFF',7,85,6.4,'Epicéa','Ayous','Carbone','Kiri','Carbone','Ayous','Epicéa'),
b('Andro','Core 7 OFF+',7,88,6.8,'Limba','Ayous','Ayous','Ayous','Ayous','Ayous','Limba'),
b('Andro','Novacell OFF',5,85,5.7,'Limba','Limba','Ayous','Limba','Limba'),
b('Andro','Timber 5 OFF',5,85,6.3,'Limba','Ayous','Kiri','Ayous','Limba'),
b('Andro','Ligna OFF+',5,85,6.8,'Epicéa','Ayous','Kiri','Ayous','Epicéa'),
b('Andro','Blax OFF',5,78,0,'Fineline','Koto','Balsa + Ayous','Koto','Fineline'),
# JOOLA
b('Joola','Vyzaryz Freeze HRD',7,87,5.8,'Koto','ALC','Ayous','Kiri','Ayous','ALC','Koto'),
b('Joola','Vyzaryz Freeze',7,85,5.7,'Limba','ALC','Limba','Kiri','Limba','ALC','Limba'),
b('Joola','Fever',7,85,0,'Limba','Carbone Meliorate','Ayous','Kiri','Ayous','Carbone Meliorate','Limba'),
b('Joola','Aruna OFF',7,88,5.7,'Hinoki','Koto','Carbone','Kiri','Carbone','Koto','Hinoki'),
b('Joola','Rossi Emotion',7,86,0,'Hinoki','Koto','3K-C','Ayous','3K-C','Koto','Hinoki'),
b('Joola','Rossi Emotion PBO-c',7,90,6.3,'Hinoki','Koto','PBO-c','Ayous','PBO-c','Koto','Hinoki'),
b('Joola','K7',7,90,6.7,'Koto','Samba rouge','Carbone Net™','Ayous','Carbone Net™','Samba rouge','Koto'),
b('Joola','Rosskopf Force',5,90,6.1,'Hinoki','Carbone','Kiri','Carbone','Hinoki'),
b('Joola','Flame Fast',5,90,6.8,'Hinoki','Ayous','Kiri','Ayous','Hinoki'),
b('Joola','Flame Extreme',5,90,8.4,'Limba','Ayous','Kiri','Ayous','Limba'),
b('Joola','Nobilis PBO-c',5,87,7.1,'Hinoki','PBO-c','Kiri','PBO-c','Hinoki'),
b('Joola','Viva',7,90,6.6,'Limba','Ayous','Ayous','Ayous','Ayous','Ayous','Limba'),
b('Joola','ZeLeBRO PBO-c',7,90,5.7,'Limba','PBO-c','Koto','Kiri','Koto','PBO-c','Limba'),
b('Joola','Energon Super PBO-c',7,90,0,'Koto','Super PBO-c','Limba','Kiri','Limba','Super PBO-c','Koto'),
b('Joola','Air Carbon',7,72,7.8,'Limba','Fineline','Carbone Net™','Balsa','Carbone Net™','Fineline','Limba'),
# NITTAKU
b('Nittaku','Acoustic',5,88,5.8,'Limba','Limba','Tung','Limba','Limba'),
b('Nittaku','Acoustic Carbon Inner',7,92,5.5,'Limba','Limba','Carbone','Tung','Carbone','Limba','Limba'),
b('Nittaku','Acoustic Carbon Outer',7,92,5.5,'Limba','Carbone','Limba','Tung','Limba','Carbone','Limba'),
b('Nittaku','Violin',5,88,5.3,'White Ash','White Ash','Kiri','White Ash','White Ash'),
b('Nittaku','Septear',7,85,6.5,'Hinoki','Hinoki','Hinoki','Hinoki','Hinoki','Hinoki','Hinoki'),
b('Nittaku','Tornado King Speed',7,90,5.7,'Limba','Carbone Kevlar™','Ayous','Kiri','Ayous','Carbone Kevlar™','Limba'),
b('Nittaku','Tornado King Power',7,90,5.8,'Koto','Ayous','Carbone Kevlar™','Ayous','Carbone Kevlar™','Ayous','Koto'),
b('Nittaku','Latika',5,88,5.8,'Limba','Epicéa','Ayous','Epicéa','Limba'),
b('Nittaku','Ma Long Five',5,89,5.8,'Koto','Pin','Ayous','Pin','Koto'),
b('Nittaku','Wang Nan',5,90,0,'Koto','Epicéa','Ayous','Epicéa','Koto'),
b('Nittaku','Ludeack',7,85,6.5,'Limba','Ayous','Ayous','Ayous','Ayous','Ayous','Limba'),
b('Nittaku','Barwell',7,88,6.6,'Noyer','Limba','Ayous','Ayous','Ayous','Limba','Noyer'),
b('Nittaku','S-Series S-7',7,85,6.2,'Epicéa','Ayous','Epicéa','Ayous','Epicéa','Ayous','Epicéa'),
b('Nittaku','S-Series S-CZ',7,85,6.0,'Epicéa','Carbone Fleece Zylon®','Ayous','Kiri','Ayous','Carbone Fleece Zylon®','Epicéa'),
# XIOM
b('Xiom','Stradivarius',7,90,0,'Koto','Aramide Carbone','Ayous','Kiri','Ayous','Aramide Carbone','Koto'),
b('Xiom','Vega Euro',7,86,5.8,'Koto','Zephylium Carbone','Ayous','Kiri','Ayous','Zephylium Carbone','Koto'),
b('Xiom','Vega Pro',7,90,5.8,'Limba','Zephylium Carbone','Ayous','Kiri','Ayous','Zephylium Carbone','Limba'),
b('Xiom','Vega Tour',7,85,5.9,'Hinoki','Zephylium Carbone','Ayous','Kiri','Ayous','Zephylium Carbone','Hinoki'),
b('Xiom','Hayabusa ZXi',7,87,5.7,'Koto','Zephylium Carbone','Ayous','Kiri','Ayous','Zephylium Carbone','Koto'),
b('Xiom','Hayabusa Zi',7,85,5.7,'Koto','Limba','Zephylium Carbone','Ayous','Zephylium Carbone','Limba','Koto'),
b('Xiom','Hugo Calderano HAL',7,85,5.8,'Koto','Axylium','Limba','Kiri','Limba','Axylium','Koto'),
b('Xiom','Ice Cream AZX',7,88,5.7,'Koto','Axylium Carbone','Limba','Kiri','Limba','Zephylium Carbone','Koto'),
b('Xiom','Feel AX',7,85,5.9,'Koto','Ayous','Aramide Carbone','Kiri','Aramide Carbone','Ayous','Koto'),
b('Xiom','Ignito',5,84,6.2,'Hinoki','Energy Zeta Carbone','Kiri','Energy Zeta Carbone','Hinoki'),
b('Xiom','Offensive S',5,87,6.1,'Limba','Limba','Ayous','Limba','Limba'),
b('Xiom','Zetro Quad',9,92,7.0,'Hinoki','Zephylium','Limba','Carbone','Kiri','Carbone','Limba'),
b('Xiom','Control OFF',5,90,7.5,'Hinoki','Aramide Carbone','Kiri','Aramide Carbone','Hinoki'),
b('Xiom','Feel HX',5,88,6.5,'Hinoki','Aramide Carbone','Kiri','Aramide Carbone','Hinoki'),
# YASAKA
b('Yasaka','Sweden Extra',5,83,5.8,'Aniégré','Limba','Ayous','Limba','Aniégré'),
b('Yasaka','Sweden Classic',5,82,5.4,'Limba','Limba','Ayous','Limba','Limba'),
b('Yasaka','Ma Lin Carbon',7,85,5.5,'Limba','Ayous','Carbone','Ayous','Carbone','Ayous','Limba'),
b('Yasaka','Ma Lin Soft Carbon',7,86,5.7,'Aniégré','Limba','Carbone','Ayous','Carbone','Limba','Aniégré'),
b('Yasaka','Atlético Balance',7,87,5.8,'Hinoki','Ayous','ALC','Ayous','ALC','Ayous','Hinoki'),
b('Yasaka','Extra Offensive',5,90,0,'Noyer','Epicéa','Ayous','Epicéa','Noyer'),
b('Yasaka','Extra Offensive 7 Power',7,88,5.7,'Noyer','Epicéa','Carbone','Kiri','Carbone','Epicéa','Noyer'),
b('Yasaka','Hinoki Leo 7',7,85,6.8,'Hinoki','Hinoki','Hinoki','Hinoki','Hinoki','Hinoki','Hinoki'),
b('Yasaka','Galaxya',7,89,6.1,'Limba','Ayous','Ayous','Ayous','Ayous','Ayous','Limba'),
# DARKER
b('Darker','7P-2A.DF',7,82,6.5,'Hinoki','Hinoki','Hinoki','Hinoki','Hinoki','Hinoki','Hinoki'),
b('Darker','7P-2A.7T',7,84,7.0,'Hinoki','Hinoki','Hinoki','Hinoki','Hinoki','Hinoki','Hinoki'),
b('Darker','7P-2A.Carbon',7,88,6.5,'Hinoki','Hinoki','Carbone','Hinoki','Carbone','Hinoki','Hinoki'),
b('Darker','5P-2A',5,82,6.5,'Hinoki','Tilleul','Hinoki','Tilleul','Hinoki'),
b('Darker','Esteem',7,80,6.5,'Hinoki','Carbone','Saule','Kiri','Saule','Carbone','Hinoki'),
b('Darker','Speed 90',1,95,9.0,'Hinoki'),
# OSP
b('OSP','Virtuoso',5,86,5.8,'Limba','Limba','Ayous','Limba','Limba'),
b('OSP','Virtuoso AC',7,87,5.6,'Limba','Limba','Aramide Carbone','Ayous','Aramide Carbone','Limba','Limba'),
b('OSP','Ultimate II',7,90,6.0,'Limba','Acajou','Ayous','Epicéa','Ayous','Acajou','Limba'),
b('OSP','Martin AC',7,90,5.0,'Limba','Aramide Carbone','Limba','Ayous','Limba','Aramide Carbone','Limba'),
# VICTAS
b('Victas','Koji Matsushita',5,87,5.4,'Limba','Epicéa','Ayous','Epicéa','Limba'),
b('Victas','Liam Pitchford',7,90,5.9,'Limba','Zexion®','Acajou','Ayous','Acajou','Zexion®','Limba'),
]

with open('/Users/nassergasmi/Documents/tennis-table/stervinou_complet_final.csv', 'w', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=FIELDS)
    writer.writeheader()
    writer.writerows(DATA)

print(f'✅ {len(DATA)} bois écrits dans stervinou_complet_final.csv')
